# Generated by Django 6.0.2 on 2026-02-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(blank=True, max_length=200)),
                ('marks_obtained', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='myapp.enrollment')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('enrollment', 'exam_name')},
            },
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
