# Generated by Django 6.0.2 on 2026-03-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mark_delete_marks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
