# Generated by Django 6.0.2 on 2026-04-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-updated_at']},
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.IntegerField(default=0, help_text='Assignment marks out of 10')),
                ('midterm', models.IntegerField(default=0, help_text='Midterm marks out of 30')),
                ('final', models.IntegerField(default=0, help_text='Final exam marks out of 60')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_records', to='myapp.enrollment')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('enrollment',)},
            },
        ),
    ]
